---
- hosts: raspberry-pi
  vars:
  tasks:
    - name: Ensure group "plex" exists
      become: yes
      group:
        name: plex
        state: present
        gid: 972
    - name: create plex user
      become: yes
      user:
        name: plex
        comment: plex
        uid: 972
        group: "972"
        state: present
    - name: install nfs-common
      become: yes
      apt:
        name: nfs-common
        state: present

    - name: create nfs mountpoint
      become: yes
      mount:
        path: /mnt
        src: 10.0.0.10:/mnt/usb1/media
        boot: yes
        fstype: nfs
        state: mounted

    - name: install transmission
      become: yes
      apt:
        name: transmission-daemon
        state: present

    - name: change transmission user to plex
      become: yes
      lineinfile:
        path: /lib/systemd/system/transmission-daemon.service
        regexp: '^User='
        line: User=plex

    - name: change config file ownership
      become: yes
      file:
        path: /etc/transmission-daemon
        group: plex
    
    - name: change config file ownership
      become: yes
      file:
        path: /etc/transmission-daemon/settings.json
        group: plex
        owner: plex

    - name: updating whitelist
      become: yes
      lineinfile:
        path: /home/plex/.config/transmission-daemon/settings.json
        regexp: '    "rpc-whitelist": "127.0.0.1",'
        line: '    "rpc-whitelist": "127.0.0.1,10.0.0.*",'
        
    - name: change config file ownership
      become: yes
      file:
        path: /var/lib/transmission-daemon/downloads
        group: plex
        owner: plex
  
    - name: download jackett
      get_url:
        url: https://github.com/Jackett/Jackett/releases/download/v0.12.1035/Jackett.Binaries.LinuxARM32.tar.gz
        dest: /tmp/Jackett.Binaries.LinuxARM32.tar.gz
  
    - name: extract archive
      become: yes
      unarchive:
        src: /tmp/Jackett.Binaries.LinuxARM32.tar.gz
        dest: /opt
        remote_src: yes

    - name: change jacket file ownership
      become: yes
      become_user: root
      file:
        path: /opt/Jackett
        group: plex
        owner: plex
        recurse: yes
  
    - name: install jackett service
      become: yes
      command: /opt/Jackett/install_service_systemd.sh

    - name: reload systemctl
      become: yes
      command: systemctl daemon-reload